export const dateFormatHourMinute = 'DD/MM/yyyy HH:mm'
export const dateFormatISO8601 = 'YYYY-MM-DDTHH:mm:ss.sss'
export const dateFormatISO8601WithZ = 'YYYY-MM-DDTHH:mm:ss. sssZ'
export const dateFormatPicker = 'DD/MM/yyyy'
export const dateFormatSendServer = 'yyyy-MM-DD'
export const dateFormatWithTime = 'DD/MM/yyyy HH:mm:ss'
export const dateFormatWithTimeSendServer = 'yyyy-MM-DD HH:mm:ss'
