export const pathSystemManager = {
  home: '/',
  dashboard: '/dashboard',
  statistic: '/dashboard/statistic',
  employerManager: '/dashboard/employers',
  employerDetail: '/dashboard/employers/view/:id',
  recruitManager: '/dashboard/recruit-manage/created',
  recruitTrash: '/dashboard/recruit-manage/trash',
  packageListCreated: '/dashboard/package-manage/list-created',
  packageCreateItem: '/dashboard/package-manage/create-item',
  packageTrash: '/dashboard/package-manage/trash',
  serviceCreated: '/dashboard/service-manage/created',
  myProfile: '/dashboard/my-profile',
  settings: '/dashboard/setting',
}
